# Generated by Django 4.2.7 on 2023-11-23 18:05

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningserviceuserprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='cleaningserviceuser',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.cleaningserviceuserprofile'),
        ),
        migrations.AddField(
            model_name='cleaningserviceuserprofile',
            name='contact',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
