# Generated by Django 4.2.7 on 2023-11-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cleaningserviceuserprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningserviceuserprofile',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
