# Generated by Django 4.2.7 on 2023-11-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cleaningserviceuserprofile_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_available',
        ),
    ]
