# Generated by Django 4.2.7 on 2023-11-28 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scheduleservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleservice',
            name='id',
        ),
        migrations.AddField(
            model_name='scheduleservice',
            name='scheduleservice_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
