# Generated by Django 4.2.7 on 2023-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_scheduleservice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleservice',
            name='completed',
        ),
        migrations.AddField(
            model_name='scheduleservice',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('completed', 'Completed')], default='booked', max_length=50, null=True),
        ),
    ]
