# Generated by Django 4.2.9 on 2024-01-11 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
