# Generated by Django 4.2.9 on 2024-01-11 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='Balance',
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('serviceprovider_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumnails', models.ImageField(blank=True, null=True, upload_to='service_provider_thumnails')),
                ('service', models.ManyToManyField(related_name='service', to='core.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serviceprovider'),
        ),
    ]
