# Generated by Django 4.2.9 on 2024-07-15 14:10

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountuser',
            old_name='organization_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='organization_logo',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('sales_person', 'Sales')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='user_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
