# Generated by Django 4.2.9 on 2024-01-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('car', 'Car Wash'), ('laundry', 'Laundry'), ('home', 'Home Cleaning')], max_length=50),
        ),
    ]
