# Generated by Django 4.2.9 on 2024-01-11 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_amount_transaction_balance_serviceprovider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='cleaningserviceuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
