# Generated by Django 4.2.9 on 2024-01-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_create_at_service_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Balance',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
