# Generated by Django 4.2.9 on 2024-07-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
