# Generated by Django 4.2.9 on 2024-07-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_medicine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
