# Generated by Django 4.2.9 on 2024-01-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_service_price_alter_transaction_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleservice',
            name='address',
            field=models.CharField(default='Acrra', max_length=50),
            preserve_default=False,
        ),
    ]
