# Generated by Django 4.2.9 on 2024-01-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_scheduleservice_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleservice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleservice',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
