# Generated by Django 4.2.9 on 2024-07-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
