# Generated by Django 4.2.9 on 2024-01-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_scheduleservice_date_alter_scheduleservice_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningserviceuser',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logo'),
        ),
    ]
