# Generated by Django 4.2.9 on 2024-01-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cleaningserviceuser_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_receipient_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
