# Generated by Django 4.2.9 on 2024-07-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_thumnail_medicine_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_thumbanils/'),
        ),
    ]
