# Generated by Django 4.2.9 on 2024-01-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cleaningserviceuser_organization_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleservice',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('completed', 'Completed'), ('ongoing', 'Ongoing')], default='booked', max_length=50, null=True),
        ),
    ]
