# Generated by Django 4.2.7 on 2023-12-15 15:03

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicefeedback',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='servicefeedback',
            name='id',
        ),
        migrations.AddField(
            model_name='servicefeedback',
            name='serviceFeedback_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cleaningserviceuserprofile',
            name='contact',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeedback',
            name='review',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeedback',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.scheduleservice'),
        ),
    ]
