# Generated by Django 4.2.7 on 2023-12-16 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_servicefeedback_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleservice',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='booked', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
